### ISSUE TITLE
Asset List Sorting: Numeric attributes are sorted as strings

### ISSUE THREAD

**Issue by topherwhite** [ywc/ywc#1]
When asset lists are sorted by a given attribute, there needs to be a way to customize whether the attribute should be sorted as a number or a string (or date or whatever). At the moment, numeric IDs are sorted as strings, which means that 999 would appear after 1000 in a sorted list (when ordered ascending).

So, this is a request for a new feature (exposed by a bug):
Add a "sortAs" attribute to the YWC asset list sorting templates.

**Comment by micheal-cooper** [comment]
![tida-news-archive-problem](https://f.cloud.github.com/assets/3095809/391482/9c67ac58-a766-11e2-98f5-ee6db1f07549.png)
I have the same problem showing up in the TIDA News archive, as the attached image shows. The ID numbers are being processed as strings rather than integers, so the newest items are appearing 19xth in the archive order. Can we reorder them by publish date?

**Comment by delaplj** [comment]
Why not a sortBy where you can set the column to sort with ?

**Comment by micheal-cooper** [comment]
Setting the TIDA News archive to sort by date published would work.

I am happy to try things, but I cannot afford to bring down TIDA, and I am not sure which xsl runs the archive search. We have the two latest news, and they are appearing correctly. The ordering problem is with the Archive where you go back to older posts.

Which file is it?

**Comment by topherwhite** [comment]
Fixed long time ago. This is now customizable when calling the ywcIntranetAssetListFull xsl template (and it cascades downward to the generic asset list templates)
